Resolved a conflict between Guava versions
Hadoop 2.X includes Guava version 11.0.2. These classes are loaded
before any application classes, which causes runtime errors (such as
java.lang.NoSuchMethodError) if the two Guava versions are not
binary compatible.
The solution is to use Maven Shade Plugin to relocate application
classes from the 'com.google' package to the 'org.jpmml.com.google'
package.